Add kibana import job
radiantlogic-devops/helm pull request #6
Opened 2022-04-26 06:44 UTC by gnanirahulnutakki

2022-04-26 16:33 UTC, pgodey commented
Rename config-map.yaml --> kibana-config-map.yaml and helm-job.yaml --> kibana-job.yaml

2022-04-26 18:39 UTC, pgodey commented on charts/fid/templates/helm-job.yaml
> +        image: centos:latest
Why are you using centos image? Can you use busybox?

2022-04-26 18:40 UTC, pgodey requested changes
Rename config-map.yaml to kibana-config-map.yaml and helm-job.yaml to kibana-job.aml

2022-04-26 19:54 UTC, gnanirahulnutakki commented on charts/fid/templates/helm-job.yaml
> +        image: centos:latest
I did not know if busybox had curl, let me try that and check if that works too

2022-04-29 04:59 UTC, pgodey requested changes

2022-04-29 04:59 UTC, pgodey commented on charts/fid/templates/helm-job.yaml
> +        - name: KIBANA_URL
I support this is kibana host, right? I would rather have one parameter called KIBANA_URL that has value like http://<host>:<port> and use that in the script.

2022-08-12 16:54 UTC, merged